Business detailed score
betagouv/territoires-en-transitions pull request #1502
Opened 2022-02-28 16:54 UTC by bertrandlalo

2022-03-01 13:51 UTC, marc-rutkowski approved these changes

2022-03-02 18:58 UTC, derfurth requested changes

2022-03-02 18:58 UTC, derfurth commented on data_layer/postgres/definitions/15-action_statut.sql
> +    avancement_detaille float[],                     -- [fait, programme, pas_fait]
il faudrait s'assurer que l'array comporte bien 3 float car le moteur en dépend

2022-03-02 19:53 UTC, derfurth approved these changes

2022-03-03 07:25 UTC, bertrandlalo commented on data_layer/postgres/definitions/15-action_statut.sql
> +begin
Trop bien, merci ! 👌

2022-03-03 14:52 UTC, closed without merging