Bannière pour indiquer qu'un épisode de maintenance est en cours
betagouv/territoires-en-transitions pull request #2198
Opened 2022-06-27 13:25 UTC by bertrandlalo

2022-07-06 07:08 UTC, derfurth commented on data_layer/sqitch/deploy/utils/maintenance.sql
> +    'Used by frontend to display a banner when maintenance is ongoing and by other dataayer tables to forbid the writing';
Pas bloquant mais si tu peux le mettre en French.

2022-07-12 11:38 UTC, derfurth requested changes

2022-07-12 11:41 UTC, bertrandlalo commented on data_layer/sqitch/deploy/utils/maintenance.sql
> +    where now() < ends_at and  now()::date = begins_at::date
Nan pcq "ongoing", ca veut juste dire "pas terminée", après c'est le front qui affiche différemment si now < begins_at ou si now > begins_at

2022-07-25 08:48 UTC, bertrandlalo commented on data_layer/tests/maintenance.sql
> +
Yes j'ajoute !

2022-07-25 09:02 UTC, derfurth commented on data_layer/sqitch/deploy/utils/maintenance.sql
> +    where now() < ends_at and  now()::date = begins_at::date
ouki !

2022-07-25 09:08 UTC, derfurth approved these changes

2022-07-25 09:19 UTC, merged