Ajout du header/footer partagés et quelques fixs sur le Design System
betagouv/territoires-en-transitions pull request #240
Opened 2021-06-28 17:28 UTC by Ynote

## Description

Cette PR ajoute l'usage du `Header` et `Footer` du dossier `components` à la racine dans l'application cliente de https://app.territoiresentransitions.fr. J'y ai mis aussi quelques petits fix par-ci par-là qui permet au Design System de mieux fonctionner dans l'application.

2021-06-28 17:40 UTC, Ynote commented on app.territoiresentransitions.fr/src/components/shared/Button/ButtonBase.svelte
> +    button {
Je ne sais pas bien pourquoi cette bordure saute dans la compilation de Tailwind. J'ai donc mis un style en dur pour l'instant vu que dans la prochaine PR, on va retirer tout Tailwind.

2021-06-29 08:00 UTC, derfurth requested changes

2021-06-29 08:00 UTC, derfurth commented on components/Layout/Header.svelte
> +    <slot name="secondary"></slot>
Peux tu rajouter un commentaire dans un docstring au début sur l'utilisation slot ?

2021-06-29 08:00 UTC, derfurth approved these changes

2021-06-29 13:28 UTC, Ynote commented on components/Layout/Header.svelte
> +    <slot name="secondary"></slot>
C'est fait !

2021-06-29 13:29 UTC, merged