Ajout vue retool pour les plans d'action
betagouv/territoires-en-transitions pull request #2667
Opened 2023-02-09 16:31 UTC by amandinejacquelin

https://www.notion.so/territoires-en-transitions/Vues-CT-plans-d-actions-312b3228b8074e33a61415a8f6127df7

2023-02-09 16:51 UTC, amandinejacquelin commented on data_layer/sqitch/deploy/retool/plan_action.sql
> +       null as nb_utilisateurs
A changer quand on aura l'historique

2023-02-10 09:30 UTC, derfurth commented
Top le generate_series ! On regardera ensemble `Vue générale “usage” de la fonctionnalité` lundi, qui passera peut être dans les stats.

2023-02-10 09:31 UTC, derfurth requested changes
Top le generate_series ! On regardera ensemble `Vue générale “usage” de la fonctionnalité` lundi, qui passera peut être dans les stats.

2023-02-15 08:46 UTC, derfurth approved these changes

2023-02-15 08:48 UTC, merged