First integration of a writtable svelte-store. Note: I by-passed hybr…
betagouv/territoires-en-transitions pull request #433
Opened 2021-07-26 12:50 UTC by bertrandlalo

- Mise en place d'un store writable Svelte
- Bypass le HybridStores pour accéder directement à l'API
- Page affectée : référentiels
- Composants affectés : ActionStatus, ProgressBar

2021-07-28 14:05 UTC, derfurth commented on codegen/codegen/action/render.py
> +# Question : where is this used ?
Ce n'est plus utilisé car on ne genère plus de fichiers html pour l'instant. On risque de s'en servir de nouveau pour que le référentiel soit consultable hors de l'appli.
Donc je serais pour marquer ce cette fonction deprecated.

2021-07-28 14:08 UTC, derfurth commented on app.territoiresentransitions.fr/src/routes/actions_referentiels/_ActionsEconomieCirculaire.svelte
> +    $: displayed, refresh() // What is this supposed to do?
lorsque displayed change (lors d'une recherche dans le parent) on appelle refresh

2021-07-28 14:13 UTC, derfurth commented on app.territoiresentransitions.fr/src/api/svelteStore.ts
> +  const epciId = getCurrentEpciId() // TODO : I guess, this should be state store as well.
current epci pourrait être dans le state, mais attention on doit garder le fait de pouvoir faire des urls par epci et donc conserver le param dans l'url

2021-07-28 14:14 UTC, derfurth commented on app.territoiresentransitions.fr/src/api/svelteStore.ts
> +const fetchAllActionsReferentielsStatusAndScoreForThisEpci = async (): Promise<void> => {
pour moi il manque un docstring mais le principe est bon !

2021-07-28 14:16 UTC, derfurth commented on codegen/codegen/action/render.py
> +# Question : where is this used ?
Après on est un peu hors sujet vis à vis de la PR

2021-07-28 14:22 UTC, derfurth commented on app.territoiresentransitions.fr/src/routes/actions_referentiels/_ActionReferentielPage.svelte
> +        await storeActions.fetchAllActionsReferentielsStatusAndScoreForThisEpci()
Ça  semble logique de mettre la responsabilité d'aller chercher les données à ce niveau mais on pourrait aussi donner la responsabilité au store de se remplir lui même.

2021-07-28 14:28 UTC, derfurth commented on app.territoiresentransitions.fr/src/api/svelteStore.ts
> +export const storeState: State = {actionsReferentielsWithStatusAndScoreById:
Si la réussite de cette fonction dépend du fait que `fetchAllActionsReferentielsStatusAndScoreForThisEpci` soit appelée pourquoi ne pas l'appeler ici plutôt que dans le composant page ?

2021-07-28 15:03 UTC, derfurth requested changes
Pour terminer et discuter cette PR je te propose de faire une session de pair la semaine prochaine. La reactivité n'étant pas bloquante pour les utilisateurs, c'est plus important que l'on soit alignés sur l'approche

2021-07-30 07:37 UTC, bertrandlalo commented on app.territoiresentransitions.fr/src/api/svelteStore.ts
> +  const epciId = getCurrentEpciId() // TODO : I guess, this should be state store as well.
Yes, je suis d'accord !

2021-07-30 07:39 UTC, bertrandlalo commented on app.territoiresentransitions.fr/src/routes/actions_referentiels/_ActionReferentielPage.svelte
> +        await storeActions.fetchAllActionsReferentielsStatusAndScoreForThisEpci()
Je suis d'accord. Mais il se remplirait entièrement au moment de la sélection de l'EPCI du coup ? 
Ca permettrait de ne pas le refaire dès qu'on se balade sur l'app. Faut bien s'assurer alors que la navigation se fait en mode single-page. Je regarde.

2021-07-30 07:41 UTC, bertrandlalo commented on app.territoiresentransitions.fr/src/api/svelteStore.ts
> +export const storeState: State = {actionsReferentielsWithStatusAndScoreById:
Pcq c'est une fonction asynchrone, je ne sais pas trop comment l'appeler, je veux bien des idées.

2021-08-04 11:04 UTC, closed without merging